# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/getting-started/

baseURL = "https://cdcaskey.github.io"
languageCode = "en-gb"
title = "Chris Caskey"

[params.author]
name = "Chris Caskey"
image = "img/author.jpg"
headline = "I do software"
bio = "Sometimes, my software is good"
links = [
  { github = "https://github.com/cdcaskey" },
  { linkedin = "https://linkedin.com/in/christopher-caskey" }
]

enableRobotsTXT = true
summaryLength = 0

[pagination]
  pagerSize = 10

[outputs]
  home = ["HTML", "RSS", "JSON"]
