baseURL = "https://cdcaskey.github.io."
languageCode = "en"
title = "Chris Caskey"

[params.author]
name = "Chris Caskey"
image = "img/author.jpg"
headline = "I do software"
bio = "Sometimes, my software is good"
links = [
  { github = "https://github.com/cdcaskey" },
  { linkedin = "https://linkedin.com/in/christopher-caskey" }
]
